# GitHub Labels Configuration
# These labels are used by workflows and release-drafter in this repository
# To sync labels: Use the github/label-sync action or create them manually

# Release notes related labels
- name: skip-release-notes
  color: "d4c5f9"
  description: Skip release notes requirement for this PR

- name: no-release-notes
  color: "d4c5f9"
  description: Alternative label to skip release notes requirement

# Category labels (used by release-drafter)
- name: feature
  color: "a2eeef"
  description: New feature or enhancement request

- name: enhancement
  color: "a2eeef"
  description: Improvement to existing functionality

- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: fix
  color: "d73a4a"
  description: Bug fix

- name: documentation
  color: "0075ca"
  description: Documentation changes

- name: docs
  color: "0075ca"
  description: Documentation changes (alias)

- name: chore
  color: "fef2c0"
  description: Maintenance tasks

- name: maintenance
  color: "fef2c0"
  description: Maintenance and upkeep

- name: dependencies
  color: "fef2c0"
  description: Dependency updates

- name: breaking
  color: "b60205"
  description: Breaking change

- name: breaking-change
  color: "b60205"
  description: Breaking change (alias)

- name: security
  color: "ee0701"
  description: Security-related changes

# Version labels (used by release-drafter version resolver)
- name: major
  color: "b60205"
  description: Major version bump

- name: minor
  color: "fbca04"
  description: Minor version bump

- name: patch
  color: "0e8a16"
  description: Patch version bump

# Excluded from changelog labels
- name: skip-changelog
  color: "eeeeee"
  description: Skip this PR from changelog

- name: duplicate
  color: "cfd3d7"
  description: This issue or pull request already exists

- name: invalid
  color: "e4e669"
  description: This doesn't seem right

- name: wontfix
  color: "ffffff"
  description: This will not be worked on
