---
extends:
  - '@commitlint/config-conventional'

rules:
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert

  scope-enum:
    - 2
    - always
    - - docker
      - compose
      - bin
      - docs
      - ci
      - config
      - security
      - deps

  subject-case:
    - 2
    - never
    - - sentence-case
      - start-case
      - pascal-case
      - upper-case

  subject-empty:
    - 2
    - never

  subject-full-stop:
    - 2
    - never
    - '.'

  type-case:
    - 2
    - always
    - lower-case

  type-empty:
    - 2
    - never

  header-max-length:
    - 2
    - always
    - 100

  body-max-line-length:
    - 2
    - always
    - 100
