---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1

ignore: |
  .git/
  node_modules/
  vendor/
