#syntax=docker/dockerfile:1.20
FROM dunglas/frankenphp:1.10.0-php8.3
LABEL maintainer="Mohamed El Mrabet <contact@cleatsquad.dev>"


RUN apt-get update && apt-get install -y --no-install-recommends \
    cron \
    libfreetype6-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libwebp-dev \
    libxslt1-dev \
    zip \
    acl \
    libnss3-tools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    install-php-extensions \
        bcmath \
        gd \
        intl \
        mbstring \
        opcache \
        pdo_mysql \
        soap \
        xsl \
        zip \
        sockets \
        ftp \
        sodium

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
