#syntax=docker/dockerfile:1.20
FROM mohelmrabet/magento-frankenphp-base:php8.4-fp1.10

LABEL maintainer="Mohamed El Mrabet <contact@cleatsquad.dev>"

USER root

# Install system packages only for DEV usage
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    mkcert \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Xdebug (DEV only)
RUN install-php-extensions xdebug

# Create the "app" user
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd --gid ${GROUP_ID} app \
    && useradd --create-home --shell /bin/bash --uid ${USER_ID} --gid app app \
    && usermod -a -G www-data app

# Fix directory permissions
RUN mkdir -p /var/www/html /data/caddy \
    && chown -R ${USER_ID}:${GROUP_ID} /var/www /data

# Ensure Caddy logs go to stdout
ENV CADDY_LOG_OUTPUT=stdout

# Copy entrypoint
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh \
    && chown ${USER_ID}:${GROUP_ID} /usr/local/bin/entrypoint.sh

# PHP app config for DEV
COPY conf/app.ini /usr/local/etc/php/conf.d/99-app.ini

# Switch to dev user
USER app

WORKDIR /var/www/html

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
